/* JOTA-JOTI GitHub Pages admin client. All private operations require a short-lived Apps Script token. */
const API_URL='https://script.google.com/macros/s/AKfycbwa3R5odIbwsPRQHHSedx4mbwRrsAE3tWLcfZX1d4Nq_QNBBDozp2TFX1jfq1eSCLwP/exec';
const TOKEN_KEY='jotajoti_admin_token_v1';
const TOKEN_EXP_KEY='jotajoti_admin_token_exp_v1';
const TAGS=['{{childFirstName}}','{{childLastName}}','{{childFullName}}','{{parentName}}','{{username}}','{{pin}}','{{participantID}}','{{youthSection}}','{{ageYear}}','{{ageGroup}}','{{email}}','{{youthEmail}}','{{parentEmail}}'];
let token=localStorage.getItem(TOKEN_KEY)||'';let users=[];let sections=[];let categories=[];let groups=[];let selected=[];let allSelected=[];let focusEl=null;
const $=id=>document.getElementById(id);
function showMsg(id,text,ok){const e=$(id);e.textContent=text;e.className='message '+(ok?'ok':'err')}
function b64url(obj){const s=JSON.stringify(obj);const bytes=new TextEncoder().encode(s);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb='jotaAdminCb_'+Date.now()+'_'+Math.floor(Math.random()*100000);const script=document.createElement('script');const q=new URLSearchParams({action,callback:cb,_:Date.now(),...params});let timer=setTimeout(()=>{cleanup();reject(new Error('The Google Apps Script server did not respond.'))},30000);window[cb]=data=>{clearTimeout(timer);cleanup();if(data&&data.success===false)reject(new Error(data.error||'Request failed'));else resolve(data)};function cleanup(){delete window[cb];script.remove()}script.onerror=()=>{clearTimeout(timer);cleanup();reject(new Error('Could not reach the Google Apps Script API.'))};script.src=API_URL+'?'+q.toString();document.body.appendChild(script)})}
function authParams(){if(!token||Date.now()>Number(localStorage.getItem(TOKEN_EXP_KEY)||0)){signOut(false);throw new Error('Admin session expired. Sign in again.')}return{token}}
async function login(password){const data=await jsonp('adminLogin',{payload:b64url({password})});token=data.token;localStorage.setItem(TOKEN_KEY,token);localStorage.setItem(TOKEN_EXP_KEY,String(Date.now()+(data.expiresInSeconds||21600)*1000));return data}
function signOut(show=true){token='';localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(TOKEN_EXP_KEY);$('app').classList.add('hidden');$('loginCard').classList.remove('hidden');$('logoutBtn').classList.add('hidden');$('senderBadge').textContent='Not signed in';if(show)showMsg('loginMsg','Signed out.',true)}
async function call(action,params={}){return jsonp(action,{...authParams(),...params})}
async function loadAll(){const [u,s,c,g,me]=await Promise.all([call('adminUsers'),call('adminSections'),call('adminCategories'),call('adminGroups'),call('adminSender')]);users=u||[];sections=s||[];categories=c||[];groups=g||[];$('senderBadge').textContent=(me.sender||'Admin')+' · '+(me.quota??'—')+' left';renderStats(me.quota);renderPeople();renderGroups();renderCategories();renderSavedGroups();refreshPreview()}
function activeUsers(){return users.filter(u=>String(u.Status||'').toLowerCase()!=='disabled')}
function renderStats(q){const a=activeUsers();$('userCount').textContent=a.length;$('parentCount').textContent=a.filter(u=>validEmail(u.ParentEmail)).length;$('youthCount').textContent=a.filter(u=>validEmail(u.Email)).length;$('quota').textContent=q??'—'}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9@._-]+/g,' ').trim()}
function matches(u,q){if(!q)return true;const n=norm(q);return [u.Name,u.Username,u.PIN,u.ParticipantID,u.ParentName,u.ParentEmail,u.Email,u.AgeGroup,u.AgeYear,u.YouthSection].some(v=>norm(v).includes(n))}
function optionHTML(u,i,kind='person'){return `<div class="option" data-i="${i}"><b>${esc(u.Name||'(no name)')}</b><span>${esc(u.YouthSection||u.AgeYear||'section not set')} · parent ${esc(u.ParentEmail||'none')} · youth ${esc(u.Email||'none')}</span></div>`}
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
function renderPeople(){const q=$('personSearch').value;const chosen=new Set(selected.map(x=>String(x.ParticipantID)));const list=activeUsers().filter(u=>!chosen.has(String(u.ParticipantID))&&matches(u,q)).sort((a,b)=>String(a.Name).localeCompare(String(b.Name))).slice(0,100);const box=$('personOptions');box.innerHTML=list.map((u,i)=>optionHTML(u,i)).join('')||'<div class="option"><span>No matching active users</span></div>';box._matches=list;box.style.display='block'}
function renderChips(){const html=selected.map(u=>`<span class="chip">${esc(u.Name||u.PIN)} <button data-remove="${esc(u.ParticipantID)}">×</button></span>`).join('');$('chips').innerHTML=html;$('allChips').innerHTML=html}
function renderGroups(){const box=$('sectionOptions');box.innerHTML=sections.map((x,i)=>`<div class="option" data-i="${i}"><b>${esc(x.label||x.value)}</b><span>${x.count} active user(s)</span></div>`).join('');box._matches=sections;$('sectionCards').innerHTML=sections.map(x=>`<button class="group-button" data-section="${esc(x.value)}"><b>${esc(x.label)}</b><span>${x.count} active users</span></button>`).join('')}
function renderSavedGroups(){const box=$('groupOptions');box.innerHTML=groups.length?groups.map((x,i)=>`<div class="option" data-i="${i}"><b>${esc(x.GroupName||x.GroupKey)}</b><span>${x.ParticipantIDs.length} participant(s)</span></div>`).join(''):'<div class="option"><span>No saved groups. Add rows to EmailGroups in the spreadsheet.</span></div>';box._matches=groups}
function renderCategories(){const box=$('activityOptions');box.innerHTML=categories.map((x,i)=>`<div class="option" data-i="${i}"><b>${esc(x.Title||x.CategoryKey)}</b><span>${esc(x.CategoryKey||'')}</span></div>`).join('');box._matches=categories;$('categoryCards').innerHTML=categories.map(x=>`<button class="group-button" data-category="${esc(x.CategoryKey)}"><b>${esc(x.Title||x.CategoryKey)}</b><span>${esc(x.CategoryKey)}</span></button>`).join('')}
function targetType(){return document.querySelector('input[name=targetType]:checked').value}function scope(){return document.querySelector('input[name=scope]:checked').value}
function recipientEmails(u){const t=targetType(),a=[];if((t==='parent'||t==='both')&&validEmail(u.ParentEmail))a.push(String(u.ParentEmail).trim().toLowerCase());if((t==='youth'||t==='both')&&validEmail(u.Email))a.push(String(u.Email).trim().toLowerCase());return [...new Set(a)]}
function scopedUsers(){const s=scope();if(s==='selected')return selected;if(s==='all')return allSelected.length?allSelected:activeUsers();if(s==='section'){const wanted=norm($('sectionSearch').dataset.value);return activeUsers().filter(u=>norm(u.YouthSection||u.AgeYear||u.AgeGroup)===wanted)}if(s==='group'){const k=String($('groupSearch').dataset.value||'').toLowerCase();const g=groups.find(x=>String(x.GroupKey).toLowerCase()===k);const ids=new Set((g?.ParticipantIDs||[]).map(String));return activeUsers().filter(u=>ids.has(String(u.ParticipantID)))}if(s==='activity'){const k=norm($('activitySearch').dataset.value);return activeUsers().filter(u=>{const raw=String(u.AllowedCategories||'').trim();return !raw||raw==='*'||raw.split(',').map(norm).includes(k)})}return []}
function refreshPreview(){const us=scopedUsers();const emails=us.flatMap(recipientEmails);const missing=us.filter(u=>recipientEmails(u).length===0).length;let text=`${us.length} active user(s) selected · ${emails.length} individual email(s)`;if(missing)text+=` · ${missing} user(s) have no valid email for this recipient type`;if(scope()==='section'&&!$('sectionSearch').dataset.value)text='Choose a youth section.';if(scope()==='activity'&&!$('activitySearch').dataset.value)text='Choose an activity category.';if(scope()==='group'&&!$('groupSearch').dataset.value)text='Choose a saved group.';$('preview').textContent=text}
function setScopeUI(){['selectedBox','sectionBox','activityBox','groupBox','allBox'].forEach(id=>$(id).classList.add('hidden'));const s=scope();if(s==='selected')$('selectedBox').classList.remove('hidden');if(s==='section')$('sectionBox').classList.remove('hidden');if(s==='activity')$('activityBox').classList.remove('hidden');if(s==='group')$('groupBox').classList.remove('hidden');if(s==='all'){$('allBox').classList.remove('hidden');if(!allSelected.length)allSelected=activeUsers().slice();selected=allSelected.slice();renderChips()}refreshPreview()}
function openBox(id){$(id).style.display='block'}function closeBox(id){setTimeout(()=>$(id).style.display='none',160)}
function choosePerson(i){const u=$('personOptions')._matches[i];if(!u)return;selected.push(u);$('personSearch').value='';$('personOptions').style.display='none';renderChips();refreshPreview()}
function chooseSection(i){const x=$('sectionOptions')._matches[i];if(!x)return;$('sectionSearch').value=x.label||x.value;$('sectionSearch').dataset.value=x.value;$('sectionOptions').style.display='none';refreshPreview()}
function chooseCategory(i){const x=$('activityOptions')._matches[i];if(!x)return;$('activitySearch').value=x.Title||x.CategoryKey;$('activitySearch').dataset.value=x.CategoryKey;$('activityOptions').style.display='none';refreshPreview()}
function payload(){
  const subject=$('subject').value.trim(),body=$('body').value.trim(),s=scope(),t=targetType();
  if(!subject)throw Error('Enter a subject.');
  if(!body)throw Error('Write an HTML message.');
  if(subject.length>180)throw Error('Subject is too long.');
  if(body.length>60000)throw Error('Keep the HTML message under 60,000 characters for reliable browser-to-Apps-Script sending.');
  const us=scopedUsers();
  if(!us.length)throw Error('No active users are selected.');
  const p={subject,htmlBody:body,scope:s,targetType:t};
  if(s==='selected'||s==='all')p.participantIds=us.map(u=>u.ParticipantID);
  if(s==='section'){if(!$('sectionSearch').dataset.value)throw Error('Choose a youth section.');p.ageGroup=$('sectionSearch').dataset.value}
  if(s==='activity'){if(!$('activitySearch').dataset.value)throw Error('Choose an activity category.');p.categoryKey=$('activitySearch').dataset.value}
  if(s==='group'){if(!$('groupSearch').dataset.value)throw Error('Choose a saved group.');p.groupKey=$('groupSearch').dataset.value}
  const drive=$('driveAttachment').value.trim();
  if(drive)p.attachments=[{driveUrl:drive}];
  const placement=$('certificatePlacement').value||'none';
  p.certificate={
    placement:placement,
    title:$('certificateTitle').value.trim(),
    subtitle:$('certificateSubtitle').value.trim(),
    message:$('certificateMessage').value.trim(),
    footer:$('certificateFooter').value.trim()
  };
  return p;
}
async function preview(){try{const p=payload();showMsg('emailMsg','Checking the live Users sheet…',true);const r=await call('adminPreview',{payload:b64url(p)});$('preview').textContent=`Ready: ${r.totalRecipients} individual email(s) · ${r.matchedUsers} matched user(s) · ${r.missingEmails} missing email(s)${r.warnings?.length?'\n'+r.warnings.join('\n'):''}`;showMsg('emailMsg','No email has been sent.',true)}catch(e){showMsg('emailMsg',e.message,false)}}
async function send(){try{const p=payload();if(!confirm('Send this email now to the live recipient list?'))return;const r=await call('adminSend',{payload:b64url(p)});let text=`Sent ${r.sent} of ${r.total} email(s).\nMatched users: ${r.matchedUsers}.`;if(r.missingEmails)text+=`\nMissing emails: ${r.missingEmails}.`;if(r.failed?.length)text+='\nFailures:\n'+r.failed.join('\n');showMsg('emailMsg',text,r.failed?.length===0);await loadAll()}catch(e){showMsg('emailMsg',e.message,false)}}
function clearComposer(){
  ['subject','body','driveAttachment'].forEach(id=>$(id).value='');
  $('certificatePlacement').value='none';
  $('certificateTitle').value='CERTIFICATE OF COMPLETION';
  $('certificateSubtitle').value='JOTA-JOTI 2026';
  $('certificateMessage').value='This certifies that {{childFullName}} has successfully taken part in JOTA-JOTI 2026 with Boulder Scout Group.';
  $('certificateFooter').value='Issued by Boulder Scout Group';
  selected=[];allSelected=[];$('personSearch').value='';$('sectionSearch').value='';$('activitySearch').value='';$('groupSearch').value='';delete $('sectionSearch').dataset.value;delete $('activitySearch').dataset.value;delete $('groupSearch').dataset.value;document.querySelector('input[name=scope][value=selected]').checked=true;setScopeUI();renderChips();$('emailMsg').className='message';refreshPreview()}
function insertTag(tag){const el=focusEl||$('body'),a=el.selectionStart||el.value.length,b=el.selectionEnd||el.value.length;el.value=el.value.slice(0,a)+tag+el.value.slice(b);el.focus();el.selectionStart=el.selectionEnd=a+tag.length}
async function findScout(q){const n=norm(q);const list=activeUsers().filter(u=>matches(u,n)).slice(0,8);const box=$('findOptions');box.innerHTML=list.map((u,i)=>optionHTML(u,i)).join('')||'<div class="option"><span>No matching active users</span></div>';box._matches=list;box.style.display='block'}
function showScout(u){$('findResult').classList.remove('hidden');$('findResult').innerHTML=`<b>${esc(u.Name||'Scout')}</b><br>PIN: ${esc(u.PIN||'—')}<br>Username: ${esc(u.Username||'—')}<br>Section: ${esc(u.YouthSection||u.AgeYear||'—')}<br>Youth email: ${esc(u.Email||'—')}<br>Parent: ${esc(u.ParentName||'—')} · ${esc(u.ParentEmail||'—')}<br><br><button class="ghost" id="useScout">Use this scout for email</button>`;$('useScout').onclick=()=>{selected=[u];document.querySelector('input[name=scope][value=selected]').checked=true;setScopeUI();renderChips();refreshPreview()}}
function setupEvents(){
 $('loginForm').onsubmit=async e=>{e.preventDefault();try{showMsg('loginMsg','Signing in…',true);const r=await login($('adminPassword').value);$('adminPassword').value='';$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('senderBadge').textContent=(r.sender||'Admin')+' · '+(r.quota??'—')+' left';await loadAll()}catch(err){showMsg('loginMsg',err.message,false)}};
 $('logoutBtn').onclick=()=>signOut(true);$('refreshBtn').onclick=async()=>{try{await loadAll();showMsg('emailMsg','Live Users data refreshed.',true)}catch(e){showMsg('emailMsg',e.message,false)}};$('previewBtn').onclick=preview;$('sendBtn').onclick=send;$('clearBtn').onclick=clearComposer;
 document.querySelectorAll('input[name=scope]').forEach(e=>e.onchange=setScopeUI);document.querySelectorAll('input[name=targetType]').forEach(e=>e.onchange=refreshPreview);
 $('personSearch').onfocus=renderPeople;$('personSearch').oninput=renderPeople;$('personOptions').onmousedown=e=>{const x=e.target.closest('.option');if(x&&$('personOptions')._matches[x.dataset.i])choosePerson(Number(x.dataset.i))};$('chips').onclick=e=>{const id=e.target.dataset.remove;if(id){selected=selected.filter(u=>String(u.ParticipantID)!==String(id));renderChips();refreshPreview()}};
 $('sectionSearch').onfocus=()=>openBox('sectionOptions');$('sectionSearch').oninput=()=>{delete $('sectionSearch').dataset.value;const q=norm($('sectionSearch').value);const m=sections.filter(x=>norm(x.label||x.value).includes(q));$('sectionOptions').innerHTML=m.map((x,i)=>`<div class="option" data-i="${i}"><b>${esc(x.label||x.value)}</b><span>${x.count} active user(s)</span></div>`).join('');$('sectionOptions')._matches=m};$('sectionOptions').onmousedown=e=>{const x=e.target.closest('.option');if(x)chooseSection(Number(x.dataset.i))};
 $('groupSearch').onfocus=()=>openBox('groupOptions');$('groupSearch').oninput=()=>{delete $('groupSearch').dataset.value;const q=norm($('groupSearch').value);const m=groups.filter(x=>norm(x.GroupName||x.GroupKey).includes(q));$('groupOptions').innerHTML=m.map((x,i)=>`<div class="option" data-i="${i}"><b>${esc(x.GroupName||x.GroupKey)}</b><span>${x.ParticipantIDs.length} participant(s)</span></div>`).join('');$('groupOptions')._matches=m};$('groupOptions').onmousedown=e=>{const x=e.target.closest('.option');if(x&&$('groupOptions')._matches[x.dataset.i]){const g=$('groupOptions')._matches[x.dataset.i];$('groupSearch').value=g.GroupName||g.GroupKey;$('groupSearch').dataset.value=g.GroupKey;$('groupOptions').style.display='none';refreshPreview()}};
 $('activitySearch').onfocus=()=>openBox('activityOptions');$('activitySearch').oninput=()=>{delete $('activitySearch').dataset.value;const q=norm($('activitySearch').value);const m=categories.filter(x=>norm(x.Title||x.CategoryKey).includes(q)||norm(x.CategoryKey).includes(q));$('activityOptions').innerHTML=m.map((x,i)=>`<div class="option" data-i="${i}"><b>${esc(x.Title||x.CategoryKey)}</b><span>${esc(x.CategoryKey)}</span></div>`).join('');$('activityOptions')._matches=m};$('activityOptions').onmousedown=e=>{const x=e.target.closest('.option');if(x)chooseCategory(Number(x.dataset.i))};
 $('allSearch').onclick=()=>{$('allOptions').innerHTML='<div class="option"><b>All active users</b><span>Every active row in Users</span></div>';$('allOptions').style.display='block'};$('allOptions').onmousedown=()=>{allSelected=activeUsers().slice();selected=allSelected.slice();$('allOptions').style.display='none';renderChips();refreshPreview()};
 $('findSearch').onfocus=()=>findScout($('findSearch').value);$('findSearch').oninput=()=>findScout($('findSearch').value);$('findOptions').onmousedown=e=>{const x=e.target.closest('.option');if(x&&$('findOptions')._matches[x.dataset.i]){$('findOptions').style.display='none';showScout($('findOptions')._matches[x.dataset.i])}};
 document.addEventListener('click',e=>{['personOptions','sectionOptions','activityOptions','allOptions','findOptions'].forEach(id=>{if(!$(id).contains(e.target)&&!$(id).previousElementSibling?.contains(e.target))$(id).style.display='none'})});
 TAGS.forEach(tag=>{const b=document.createElement('button');b.className='tag';b.type='button';b.textContent=tag;b.onclick=()=>insertTag(tag);$('tags').appendChild(b)});$('subject').onfocus=()=>focusEl=$('subject');$('body').onfocus=()=>focusEl=$('body');
 document.querySelectorAll('.group-button').forEach(()=>{});$('sectionCards').onclick=e=>{const b=e.target.closest('[data-section]');if(b){document.querySelector('input[name=scope][value=section]').checked=true;setScopeUI();$('sectionSearch').value=b.dataset.section;$('sectionSearch').dataset.value=b.dataset.section;refreshPreview()}};$('categoryCards').onclick=e=>{const b=e.target.closest('[data-category]');if(b){document.querySelector('input[name=scope][value=activity]').checked=true;setScopeUI();$('activitySearch').value=b.dataset.category;$('activitySearch').dataset.value=b.dataset.category;refreshPreview()}};
}
async function boot(){setupEvents();if(token&&Date.now()<Number(localStorage.getItem(TOKEN_EXP_KEY)||0)){try{$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');await loadAll()}catch(e){signOut(false)}}}
boot();
